# .gqlgen.yml example
#
# Refer to https://gqlgen.com/config/
# for detailed .gqlgen.yml documentation.

schema: schema.graphql
exec:
  filename: graph/generated.go
model:
  filename: model/generated.go
resolver:
  filename: graph/resolver.go
  type: Resolver

models:
  User:
    model: github.com/exfly/manageme/model.User
  Mood:
    model: github.com/exfly/manageme/model.Mood
