schema: schema.graphql
exec:
  filename: graph/generated.go
model:
  filename: model/generated.go


models:
  User:
    model: github.com/exfly/manageme/model.User
  Mood:
    model: github.com/exfly/manageme/model.Mood
